
DROP TABLE USER;
DROP TABLE IDEA;
DROP TABLE COMMENT;


CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT primary key,
    FIRST_NAME varchar(255),
    LAST_NAME varchar(255),
    EMAIL varchar(255),
    IMG_URL varchar(255),
    SPACES varchar(255)
);


CREATE TABLE IDEA (
    IDEA_ID INT AUTO_INCREMENT primary key,
    TITLE varchar(255),
    DESCRIPTION varchar(255),
    USER_KEY INT
);

CREATE TABLE COMMENT (
    COMMENT_ID INT AUTO_INCREMENT primary key,
    DESCRIPTION varchar(255),
    UPVOTE INT,
    DOWNVOTE INT
);



/*
INSERT INTO IDEA (IDEA_ID, TITLE, DESCRIPTION, USER_KEY) VALUES(1, 'FB LOGIN','ADD A BUTTON', 1);
INSERT INTO IDEA (IDEA_ID, TITLE, DESCRIPTION, USER_KEY) VALUES(2, 'COFFEE MACHINE','NEED COFFEE', 2);
INSERT INTO IDEA (IDEA_ID, TITLE, DESCRIPTION, USER_KEY) VALUES(3, 'MANAGER SUCKS','CAN WE FIRE THEM', 3);
*/